/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VehiclesRouteImport } from './routes/vehicles'
import { Route as TripsRouteImport } from './routes/trips'
import { Route as TrackingRouteImport } from './routes/tracking'
import { Route as PredictionsRouteImport } from './routes/predictions'
import { Route as DriversRouteImport } from './routes/drivers'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CustomerTrackingRouteImport } from './routes/customer-tracking'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AnalyticsRouteImport } from './routes/analytics'

const VehiclesRoute = VehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsRoute = TripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackingRoute = TrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictionsRoute = PredictionsRouteImport.update({
  id: '/predictions',
  path: '/predictions',
  getParentRoute: () => rootRouteImport,
} as any)
const DriversRoute = DriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerTrackingRoute = CustomerTrackingRouteImport.update({
  id: '/customer-tracking',
  path: '/customer-tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/analytics': typeof AnalyticsRoute
  '/assistant': typeof AssistantRoute
  '/customer-tracking': typeof CustomerTrackingRoute
  '/dashboard': typeof DashboardRoute
  '/drivers': typeof DriversRoute
  '/predictions': typeof PredictionsRoute
  '/tracking': typeof TrackingRoute
  '/trips': typeof TripsRoute
  '/vehicles': typeof VehiclesRoute
}
export interface FileRoutesByTo {
  '/analytics': typeof AnalyticsRoute
  '/assistant': typeof AssistantRoute
  '/customer-tracking': typeof CustomerTrackingRoute
  '/dashboard': typeof DashboardRoute
  '/drivers': typeof DriversRoute
  '/predictions': typeof PredictionsRoute
  '/tracking': typeof TrackingRoute
  '/trips': typeof TripsRoute
  '/vehicles': typeof VehiclesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/analytics': typeof AnalyticsRoute
  '/assistant': typeof AssistantRoute
  '/customer-tracking': typeof CustomerTrackingRoute
  '/dashboard': typeof DashboardRoute
  '/drivers': typeof DriversRoute
  '/predictions': typeof PredictionsRoute
  '/tracking': typeof TrackingRoute
  '/trips': typeof TripsRoute
  '/vehicles': typeof VehiclesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/analytics'
    | '/assistant'
    | '/customer-tracking'
    | '/dashboard'
    | '/drivers'
    | '/predictions'
    | '/tracking'
    | '/trips'
    | '/vehicles'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/analytics'
    | '/assistant'
    | '/customer-tracking'
    | '/dashboard'
    | '/drivers'
    | '/predictions'
    | '/tracking'
    | '/trips'
    | '/vehicles'
  id:
    | '__root__'
    | '/analytics'
    | '/assistant'
    | '/customer-tracking'
    | '/dashboard'
    | '/drivers'
    | '/predictions'
    | '/tracking'
    | '/trips'
    | '/vehicles'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AnalyticsRoute: typeof AnalyticsRoute
  AssistantRoute: typeof AssistantRoute
  CustomerTrackingRoute: typeof CustomerTrackingRoute
  DashboardRoute: typeof DashboardRoute
  DriversRoute: typeof DriversRoute
  PredictionsRoute: typeof PredictionsRoute
  TrackingRoute: typeof TrackingRoute
  TripsRoute: typeof TripsRoute
  VehiclesRoute: typeof VehiclesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vehicles': {
      id: '/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof VehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips': {
      id: '/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof TripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracking': {
      id: '/tracking'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof TrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictions': {
      id: '/predictions'
      path: '/predictions'
      fullPath: '/predictions'
      preLoaderRoute: typeof PredictionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drivers': {
      id: '/drivers'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof DriversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-tracking': {
      id: '/customer-tracking'
      path: '/customer-tracking'
      fullPath: '/customer-tracking'
      preLoaderRoute: typeof CustomerTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AnalyticsRoute: AnalyticsRoute,
  AssistantRoute: AssistantRoute,
  CustomerTrackingRoute: CustomerTrackingRoute,
  DashboardRoute: DashboardRoute,
  DriversRoute: DriversRoute,
  PredictionsRoute: PredictionsRoute,
  TrackingRoute: TrackingRoute,
  TripsRoute: TripsRoute,
  VehiclesRoute: VehiclesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
